<?php
/**
 * @file
 * .module file of Tripal BLAST.
 */

use Drupal\Core\Url;
use \Drupal\Core\Link;
use Drupal\Core\Render\Markup;
use Drupal\Core\Hook\Attribute\LegacyHook;

/**
 * Implements hook_theme().
 * Used by Tripal BLAST UI page.
 *
 * @see templates in /templates
 */
#[LegacyHook]
function tripal_blast_theme($existing, $type, $theme, $path) {
  return \Drupal::service('tripal_blast.hook_service')->theme($existing, $type, $theme, $path);
}
