<?php

require_once 'includes/blast_ui.blastn.inc';
require_once 'includes/blast_ui.blastp.inc';
require_once 'includes/blast_ui.node.inc';

function blast_ui_menu() {

  $items['blast'] = array(
    'title' => 'BLAST',
    'page callback' => 'drupal_get_form',
    // Add in a page callback/aguements for a drupal form letting you choose nucl. or protein and then redirecting you
    'page arguments' => array('blast_nucleotide_form'),
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
    'expanded' => TRUE
  );

  $items['blast/blastn'] = array(
    'title' => 'Nucleotide BLAST',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('blast_nucleotide_form'), //Need to change these to use the blast_ui prefix instead of just blast

    // Added the following
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM
  );

  $items['blast/blastp'] = array(
    'title' => 'Protein BLAST',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('blast_protein_form'), //Need to change these to use the blast_ui prefix instead of just blast

    // Added the following
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM
  );

  return $items;
}