<?php
/**
 * @file
 * Contains class definition of Tripal BLAST Jobs service.
 */
namespace Drupal\tripal_blast\Services;

use Drupal\Core\Render\Markup;
use Drupal\tripal\Services\TripalJob;
use Drupal\tripal\Services\TripalLogger;
use Drupal\tripal_blast\Services\TripalBlastProgramHelper;

class TripalBlastJobService {

  /**
   * A list of the file types that are generated by BLAST.
   *
   * @var array
   *  Each element of the list should contain the following:
   *  - id: unique identifier which is used in the job object.
   *  - label: readable name used in the BLAST Results.
   *  - suffix: the file ending for this type.
   */
  public static array $file_types = [
    ['id' => 'archive', 'label' => 'Archive', 'suffix' => '.asn'],
    ['id' => 'xml', 'label' => 'XML', 'suffix' => '.xml'],
    ['id' => 'tsv', 'label' => 'Tab-Delimited', 'suffix' => '.tsv'],
    ['id' => 'html', 'label' => 'Alignment', 'suffix' => '.html'],
    ['id' => 'gff', 'label' => 'GFF3', 'suffix' => '.gff']
  ];
  /**
   * Constructs a new TripalBlastJobService object.
   *
   * @param \Drupal\tripal\Services\TripalLogger|null $logger
   *   The Tripal logger service.
   */
  public function __construct(?TripalLogger $logger = NULL) {
    $this->logger = $logger ?? \Drupal::service('tripal.logger');
  }
  /**
   * The Tripal logger service.
   *
   * @var \Drupal\tripal\Services\TripalLogger
   */
  protected TripalLogger $logger;

  /**
   * Retrieve the number or recent jobs.
   */
  public function jobsCountRecentJobs() {
    return (isset($_SESSION['blast_jobs'])) ? sizeof($_SESSION['blast_jobs']) : 0;
  }

  /**
   * Return a list of recent blast jobs to be displayed to the user.
   *
   * @param $programs
   *   An array of blast programs you want jobs to be displayed for (ie: blastn, blastx, tblastn, blastp)
   *
   * @return
   *   An array of recent jobs.
   */
  public function jobsGetRecentJobs($programs = []) {
    $filter_jobs = !empty($programs);

    // Retrieve any recent jobs from the session variable.
    if (isset($_SESSION['blast_jobs'])) {

      $jobs = [];
      foreach ($_SESSION['blast_jobs'] as $job_secret) {
        $add = TRUE;

        $job_id = self::jobsBlastRevealSecret($job_secret);
        if ($job = self::jobsGetJobByJobId($job_id)) {
          // @TODO: Check that the results are still available.
          // This is meant to replace the arbitrary only show jobs executed less than 48 hrs ago.

          // Remove jobs from the list that are not of the correct program.
          if ($filter_jobs AND !in_array($job->program, $programs)) {
            $add = FALSE;
          }

          if ($add) {
            $job->query_summary = self::jobsFormatQueryHeaders($job->files->query);
            $jobs[] = $job;
          }
        }
      }

      return $jobs;
    }
    else {
      return [];
    }
  }

  /**
   * Create a table listing recent BLAST jobs.
   *
   * @param $program
   *   An array of program to filter from the jobs history.
   *
   * @return array
   *   Form API table type.
   */
  public function jobsCreateTable($program = []) {
    $jobs = self::jobsGetRecentJobs($program);
    $jobs_table = [];
    $headers = ['Query Information', 'Search Target', 'Date Requested', '-'];

    $rows = [];
    foreach($jobs as $job) {
      $result_link = '/blast/report/' . self::jobsBlastMakeSecret($job->job_id);

      $rows[] = [
        $job->query_summary,
        $job->blastdb->db_name,
        \Drupal::service('date.formatter')->format($job->date_submitted, 'medium'),
        Markup::create('<a href="' . $result_link . '">See Results</a>')
      ];
    }

    $jobs_table = [
      '#type' => 'table',
      '#title' => 'Recent Jobs',
      '#header' => $headers,
      '#rows' => $rows,
      '#empty' => t('0 Recent Jobs'),
    ];

    return $jobs_table;
  }

  /**
   * Makes the tripal job_id unrecognizable.
   *
   * @param $job_id
   *   The tripal job_id of the blast you want to make secret.
   *
   * @return
   *   A short string representing the job_id.
   */
  public function jobsBlastMakeSecret($job_id) {
    $mapping = self::jobsBlastMapSecret();
    $secret = str_replace(array_keys($mapping), $mapping, $job_id);

    return $secret;
  }

  /**
   * Reveals the true job_id for your secret blast result.
   *
   * @param $secret
   *    The job_id previously made secret by blast_ui_make_secret().
   *
   * @return
   *    The revealed tripal job_id.
   */
  public function jobsBlastRevealSecret($secret) {
    $mapping = self::jobsBlastMapSecret(TRUE);
    $job_id = str_replace(array_keys($mapping), $mapping, $secret);

    if (is_numeric($job_id)) {
      // Check that the job_id exists if it is an integer.
      $exists = self::jobsGetJobByJobId($job_id);

      if ($exists) {
        return $job_id;
      }
      else {
        $this->logger->error('Unable to decode the blast job_id from :id.', [':id' => $secret]);
      }
    }
    else {
      // Last ditch effort: maybe this job was encoded before the upgrade?
      $job_id = base64_decode($secret);

      if (is_numeric($job_id)) {
        $exists = self::jobsGetJobByJobId($job_id);

        if ($exists) {
          return $job_id;
        }
        else {
          $this->logger->error('Unable to decode the blast job_id from :id.', [':id' => $secret]);
        }
      }
      else {
        $this->logger->error('Unable to decode the blast job_id from :id.', [':id' => $secret]);
      }
    }

    return FALSE;
  }

  /**
   * A single location for keeping track of the mapping used in our secrets.
   */
  public function jobsBlastMapSecret($reveal = FALSE) {
    $mapping = [
      1 => 'P',
      2 => 'sA',
      3 => 'b',
      4 => 'Q',
      5 => 'Hi',
      6 => 'yt',
      7 => 'f',
      8 => 'zE',
      9 => 'Km',
      0 => 'jVo',
    ];

    // Since this is an open-source module with all the code publically available,
    // our secret is not very secret... We are ok with this since the liklihood of
    // profiting by stealing random blast results is pretty low. That said, if this bothers
    // you, feel free to implement the following function in a private module to change
    // this mapping to something that cannot easily be looked up on github. ;-).
    // NOTE: Ensure that the mapping you come up with is unique to ensure that the
    // job_id can be consistently revealed or your users might end up unable to find
    // their own blast results...
    if (function_exists('private_make_mapping_ultra_secret')) {
      $mapping = private_make_mapping_ultra_secret($mapping);
    }

    if ($reveal) {
      return array_flip($mapping);
    }
    else {
      return $mapping;
    }
  }

  /**
   * Get BLAST job by job_id.
   *
   * @param $job_id
   *   Unique id of BLAST job request.
   * @param array $options
   *   Supported keys include:
   *   - skip_file_check: If FALSE then check that the result files exist.
   *     Default is FALSE.
   *
   * @return object
   *   Job record matching the job id.
   */
  public function jobsGetJobByJobId($job_id, array $options = []) {

    // Set defaults.
    $options += [
      'skip_file_check' => FALSE
    ];

    $query = \Drupal::database()->select('blastjob', 'jobs');
    $query->fields('jobs');
    $query->condition('jobs.job_id', $job_id);

    $blastjob = $query->execute()->fetchObject();
    if (!$blastjob) {
      return FALSE;
    }

    $tripaljob = new TripalJob;
    $tripaljob->load($job_id);
    $tripal_job = $tripaljob->getJob();

    $job = new \stdClass();
    $job->job_id = $job_id;
    $job->program = $blastjob->blast_program;
    $job->options = unserialize($blastjob->options);
    $job->date_submitted = $tripal_job->submit_date;
    $job->date_started = $tripal_job->start_time;
    $job->date_completed = $tripal_job->end_time;

    // TARGET BLAST DATABASE.
    if ($blastjob->target_blastdb) {
      // If a provided blast database was used then load details.
      $config = \Drupal::service('tripal_blast.database_service')
        ->getDatabaseConfig($blastjob->target_blastdb);

      $job->blastdb = new \stdClass();
      $job->blastdb->db_name = $config['name'];
      $job->blastdb->db_path = $config['path'];
      $job->blastdb->linkout = new \stdClass();
      $job->blastdb->linkout->none = $config['dbxref_linkout_type'];
      $job->blastdb->db_dbtype = $config['dbtype'];
    }
    else {
      // Otherwise the user uploaded their own database so provide what information we can.
      $job->blastdb = new \stdClass();
      $job->blastdb->db_name = 'User Uploaded';
      $job->blastdb->db_path = $blastjob->target_file;
      $job->blastdb->linkout = new \stdClass();
      $job->blastdb->linkout->none = TRUE;

      if ($job->program == 'blastp' OR $job->program == 'tblastn') {
        $job->blastdb->db_dbtype = 'protein';
      }
      else {
        $job->blastdb->db_dbtype = 'nucleotide';
      }
    }

    // FILES.
    $job->files = new \stdClass();
    $job->files->query = $blastjob->query_file;
    $job->files->target = $blastjob->target_file;

    // - Results files.
    $job->files->result = [];

    //   Note: the result_filestub is the absolute path to the files without the
    //   file type suffix (ie: .xml, .tsv, .html, .gff, .asn). To determine the
    //   URI we need to strip the DRUPAL_ROOT from the absolute path.
    $public_path = \Drupal::service('file_system')->realpath('public://');
    $absolute_path = $blastjob->result_filestub;
    //   If the absolute path is within the public:// directory then we can use
    //   the public:// stream wrapper to create the URI.
    if (str_starts_with($absolute_path, $public_path)) {
      $relative = substr($absolute_path, strlen($public_path));
      $uri = 'public://' . ltrim($relative, '/');
    }
    //   Otherwise we will just strip the DRUPAL_ROOT from the absolute path to
    //   create a relative URI.
    else {
      $uri = str_replace(DRUPAL_ROOT . DIRECTORY_SEPARATOR, '', $blastjob->result_filestub);
    }

    //   Now let's loop through the file types and create the absolute path
    //   and URI for each.
    foreach (self::$file_types as $details) {
      $type = $details['id'];
      $suffix = $details['suffix'];
      $label = $details['label'];

      // Initialize the file result structure for this type.
      $job->files->result[$type] = [];
      $job->files->result[$type]['absolute_path'] = NULL;
      $job->files->result[$type]['uri'] = NULL;
      $job->files->result[$type]['label'] = $label;

      // If this file exists then we can add it to the job.
      if (file_exists($blastjob->result_filestub . $suffix) || $options['skip_file_check']) {
        $job->files->result[$type]['absolute_path'] = $blastjob->result_filestub . $suffix;
        $job->files->result[$type]['uri'] = $uri . $suffix;
        $job->files->result[$type]['label'] = $label;
      }
    }

    return $job;
  }

  /**
   * Create a new BLAST Tripal job.
   *
   * @param $job_parameters
   *   An array of parameters used to execute the blast.
   *   The following keys are supported:
   *   - blast_program: The BLAST program to execute (ie: blastn, tblastn, tblastx, blastp, blastx).
   *   - target_blastdb: The tripal_blast_database id of the target database to search against.
   *   - target_file: The full path to the file containing the target database.
   *   - query_file: The full path to the file containing the query sequence.
   *   - result_filestub: The full path to the file where the results will be written (without file type suffix).
   *   - options: An array of additional options where the key is the name of the option used by BLAST (ie: 'num_alignments') and the value is relates to this particular BLAST job (ie: 250).
   *
   * @return int|null
   *   The tripal job_id of the newly created BLAST job.
   */
  public function createBlastJob(array $job_parameters): ?int {

    // Validate the blast_program parameter.
    if (!array_key_exists('blast_program', $job_parameters)) {
      throw new \Exception("Missing required parameter 'blast_program' when creating a new BLAST job.");
    }
    elseif (!in_array($job_parameters['blast_program'], ['blastn', 'tblastn', 'tblastx', 'blastp', 'blastx'])) {
      throw new \Exception("Invalid value for parameter 'blast_program' when creating a new BLAST job. The value supplied was: " . $job_parameters['blast_program']);
    }

    // We need either the 'target_blastdb' or 'target_file' parameter to be set.
    if (!array_key_exists('target_blastdb', $job_parameters) AND !array_key_exists('target_file', $job_parameters)) {
      throw new \Exception("Missing required parameter 'target_blastdb' or 'target_file' when creating a new BLAST job.");
    }
    // If the target_blastdb is set then we need to make sure it exists and set
    // the target_file to the path of the database.
    elseif (array_key_exists('target_blastdb', $job_parameters)) {
      if (is_numeric($job_parameters['target_blastdb'])) {
        // If the target_blastdb is set then we need to make sure it exists.
        $database_config = \Drupal::service('tripal_blast.database_service')
          ->getDatabaseConfig($job_parameters['target_blastdb']);

        if (!$database_config) {
          throw new \Exception("The value supplied for parameter 'target_blastdb' does not exist. The value supplied was: " . $job_parameters['target_blastdb']);
        }
        else {
          // If the target_blastdb is set then we need to make sure the target_file is set to the path of the database.
          $job_parameters['target_file'] = $database_config['path'];
        }
      }
      else {
        throw new \Exception("Invalid value for parameter 'target_blastdb' when creating a new BLAST job. The value supplied was: " . $job_parameters['target_blastdb']);
      }
    }

    // Now check the query file parameter.
    if (!array_key_exists('query_file', $job_parameters)) {
      throw new \Exception("Missing required parameter 'query_file' when creating a new BLAST job.");
    }
    elseif (!file_exists($job_parameters['query_file'])) {
      throw new \Exception("The value supplied for parameter 'query_file' does not exist. The value supplied was: " . $job_parameters['query_file']);
    }

    // Set default for result_filestub parameter if not set.
    if (!array_key_exists('result_filestub', $job_parameters)) {
      // We want to save all result files (.asn, .xml, .tsv, .html) in the public files directory.
      // Usually [drupal root]/sites/default/files.
      $output_dir = tripal_get_files_dir('tripal_blast');
      $job_parameters['result_filestub'] = $output_dir . date('YMd_His') . '.blast';
    }

    // If advanced options are not set, we will set it to an empty array.
    if (!array_key_exists('options', $job_parameters)) {
      $job_parameters['options'] = [];
    }

    // Create the tripal job.
    $trpjob_args = [
      $job_parameters['blast_program'],
      $job_parameters['query_file'],
      $job_parameters['target_file'],
      $job_parameters['result_filestub'],
      serialize($job_parameters['options'])
    ];
    $job_id = tripal_add_job(
      t('BLAST (@program): @query', array('@program' => $job_parameters['blast_program'], '@query' => $job_parameters['query_file'])),
      'blast_job',
      ['Drupal\tripal_blast\Services\TripalBlastJobService', 'runJob'],
      $trpjob_args,
      \Drupal::currentUser()->id()
    );

    // Now save the tripal job_id into the params.
    if (is_numeric($job_id)) {
      $job_parameters['job_id'] = (int) $job_id;
    }
    else {
      throw new \Exception("Unable to create a Tripal job for the BLAST request. The parameters were: " . print_r($job_parameters, true));
    }

    // Finally, use this helper method to save the job parameters into the
    // blastjob table and return the job object.
    $this->jobsSave($job_parameters);
    return $job_parameters['job_id'];
  }

  /**
   * Save job information/parameters into blastjob table.
   *
   * @param $job_parameters
   *   Parameters used to execute the job.
   */
  protected function jobsSave($job_parameters) {
    \Drupal::service('database')->insert('blastjob')
      ->fields([
        'job_id' => $job_parameters['job_id'],
        'blast_program' => $job_parameters['blast_program'],
        'target_blastdb' => $job_parameters['target_blastdb'],
        'target_file' => $job_parameters['target_file'],
        'query_file' => $job_parameters['query_file'],
        'result_filestub' => $job_parameters['result_filestub'],
        'options' => is_array($job_parameters['options']) ? serialize($job_parameters['options']) : $job_parameters['options']
      ])
      ->execute();
  }

  /**
   * Generate the BLAST command for execution.
   *
   * @param string $program
   *   The BLAST program to execute. Supported values include 'blastn',
   *   'tblastn', tblastx', 'blastp','blastx'.
   * @param string $query
   *   The full path to the file containing the query sequence.
   * @param string $database
   *   The full path to the file containing the BLAST database.
   * @param array $output_file
   *   The output file paths where the key is the file type (ie: 'xml', 'tsv',
   *   'html', 'gff', 'archive') and the value is the full path to the file.
   * @param array &$options
   *   The BLAST options.
   *
   * @return array
   *   The two BLAST commands. Specifically, the first command is the BLAST
   *   command and the second command is the BLAST formatter command.
   *
   * @throws /Exception
   *   Throws an exception if the any of the following do not exist:
   *   - BLAST database
   *   - Specific BLAST Command
   *   - BLAST Formatter Command
   */
  public function getBlastCommand(string $program, string $query, string $database, array $output_file, array &$options): array {

    // Gap open and gap extend costs are required for blastn and blastp.
    // We are given them in integer pairs (ie: 5_2) but BLAST requires them to
    // be passed in as separate options.
    if (array_key_exists('gapopen', $options)) {
      $gap_parts = TripalBlastProgramHelper::programSetGap($options['gapopen']);
      if (array_key_exists('gapopen', $gap_parts)) {
        $options['gapopen'] = $gap_parts['gapopen'];
      }
      if (array_key_exists('gapextend', $gap_parts)) {
        $options['gapextend'] = $gap_parts['gapextend'];
      }
    }

    // Allow administrators to use an absolute path for these commands.
    // Defaults to using $PATH.
    $blast_path = \Drupal::config('tripal_blast.settings')
      ->get('tripal_blast_config_general.path');

    $blast_threads = \Drupal::config('tripal_blast.settings')
      ->get('tripal_blast_config_general.threads');

    // Strip the extension off the BLAST target
    $suffix = [
      '.ndb',
      '.nhr',
      '.nin',
      '.not',
      '.nsq',
      '.ntf',
      '.nto',
      '.pdb',
      '.phr',
      '.pin',
      '.pot',
      '.psq',
      '.ptf',
      '.pto'
    ];

    $database = str_replace($suffix, '', $database);

    // Check that the database exists before trying to execute the job.
    if (!(file_exists($database . '.nsq') or file_exists($database . '.psq'))) {
      throw new \Exception("Unable to find the BLAST database (ie: @db). Please ensure you have supplied the absolute path not including the file format endings.", ['@db' => $database]);
    }

    // The BLAST executeable.
    $program = $blast_path . $program;
    if (!file_exists($program)) {
      throw new \Exception("Unable to find the BLAST executable (ie: /usr/bin/blastn). This can be changed in the admin settings; you supplied: @command", ['@command' => $program]);
    }

    // The blast db formatter executable.
    $blast_formatter_command = $blast_path . 'blast_formatter';
    if (!file_exists($blast_formatter_command)) {
      throw new \Exception("Unable to find the BLAST Formatter executable (ie: /usr/bin/blast_formatter). This can be changed in the admin settings; you supplied: @command", ['@command' => $blast_formatter_command]);
    }

    // Note: all variables are escaped (adds single quotes around their values) for security reasons.
    $blast_cmd = escapeshellarg($program) . ' -query ' . escapeshellarg($query) . ' -db ' . escapeshellarg($database) . ' -out ' . escapeshellarg($output_file['archive']) . ' -outfmt=11';
    if (!empty($options)) {
      foreach ($options as $opt => $val) {
        $val = trim($val);
        if (!empty($val)) {
          // We want to escape all the option values since they were supplied via
          // user input. These values should also have been checked in the
          // advanced form _validate functions but this adds an extra layer of
          // protection.
          $blast_cmd .= ' -' . escapeshellarg($opt) . ' ' . escapeshellarg($val);
        }
      }
    }

    // Setting the value of threads by admin page
    $blast_cmd .= ' -num_threads ' . escapeshellarg($blast_threads);

    return [$blast_cmd, $blast_formatter_command];
  }

  /**
   * Run BLAST (should be called from the command-line)
   *
   * @param $program
   *   Which BLAST program to run (ie: 'blastn', 'tblastn', tblastx', 'blastp','blastx')
   * @param $query
   *   The full path and filename of the query FASTA file
   * @param $database
   *   The full path and filename prefix (excluding .nhr, .nin, .nsq, etc.)
   * @param $output_filestub
   *   The filename (not including path) to give the results. Should not include file type suffix
   * @param $options
   *   An array of additional option where the key is the name of the option used by
   *   BLAST (ie: 'num_alignments') and the value is relates to this particular
   *   BLAST job (ie: 250)
   */
  public static function runJob($program, $query, $database, $output_filestub, $options, $job_id = NULL) {
    $logger = \Drupal::service('tripal.logger');

    $output_file['archive'] = $output_filestub . '.asn';
    $output_file['xml'] = $output_filestub . '.xml';
    $output_file['tsv'] = $output_filestub . '.tsv';
    $output_file['html'] = $output_filestub . '.html';
    $output_file['gff'] = $output_filestub . '.gff';

    try {
      $job_service = \Drupal::service('tripal_blast.job_service');
      [$blast_cmd, $blast_formatter_command] = $job_service->getBlastCommand($program, $query, $database, $output_file, $options);
    }
    catch (\Exception $e) {
      $logger->error("Unable to generate the BLAST command for execution. The error was: @error", ['@error' => $e->getMessage()]);
      return FALSE;
    }

    print "\nExecuting $program\n\n";
    print "Query: $query\n";
    print "Database: $database\n";
    print "Results File: " . $output_file['archive'] . "\n";

    print "Options:\n";
    foreach ($options as $opt => $val) {
      $val = trim($val);
      if (!empty($val)) {
        print "\t$opt: $val\n";
      }
    }

    print "\nExecuting the following BLAST command:\n" . $blast_cmd . "\n";
    system($blast_cmd);

    if (!file_exists($output_file['archive'])) {
      $logger->error("BLAST did not complete successfully as is implied by the lack of output file (%file). The command run was @command", ['%file' => $output_file['archive'], '@command' => $blast_cmd]);

      return FALSE;
    }

    print "\nGenerating additional download formats...\n";

    print "\tXML\n";
    $format_cmd = escapeshellarg($blast_formatter_command) . ' -archive ' . escapeshellarg($output_file['archive']) . ' -outfmt 5 -out ' . escapeshellarg($output_file['xml']);
    print "\t\tExecuting $format_cmd\n\n";
    system($format_cmd);

    if (!file_exists($output_file['xml'])) {
      $logger->error("Unable to convert BLAST ASN.1 archive to XML (%archive => %file).", ['%archive' => $output_file['archive'], '%file' => $output_file['xml']]);
    }

    print "\tTab-delimited\n";
    $format_cmd = escapeshellarg($blast_formatter_command) . ' -archive ' . escapeshellarg($output_file['archive']) . ' -outfmt 7 -out ' . escapeshellarg($output_file['tsv']);
    print "\t\tExecuting $format_cmd\n\n";
    system($format_cmd);

    if (!file_exists($output_file['tsv'])) {
      $logger->warning("Unable to convert BLAST ASN.1 archive to Tabular Output (%archive => %file).", ['%archive' => $output_file['archive'], '%file' => $output_file['tsv']]);
    }

    print "\tGFF\n";
    $job_service = \Drupal::service('tripal_blast.job_service');
    $job_service->jobsConvertTSVtoGFF3($output_file['tsv'], $output_file['gff']);

    if (!file_exists($output_file['gff'])) {
      $logger->warning("Unable to convert BLAST Tabular Output to GFF Output (%archive => %file).", ['%archive' => $output_file['archive'], '%file' => $output_file['gff']]);
    }

    print "\tHTML (includes alignments)\n";
    $format_cmd = escapeshellarg($blast_formatter_command) . ' -archive ' . escapeshellarg($output_file['archive']) . ' -outfmt 0 -out ' . escapeshellarg($output_file['html']) . ' -html';
    print "\t\tExecuting $format_cmd\n\n";
    system($format_cmd);

    if (!file_exists($output_file['html'])) {
      $logger->warning("Unable to convert BLAST ASN.1 archive to HTML Output (%archive => %file).", ['%archive' => $output_file['archive'], '%file' => $output_file['html']]);
    }

    print "\nDone!\n";
  }

  /**
   * Summarize a fasta file based on it's headers.
   *
   * @param $file
   *   The full path to the FASTA file.
   *
   * @return
   *   A string describing the number of sequences and often including the first query header.
   */
  public function jobsFormatQueryHeaders($file) {
    $headers = [];
    exec('grep ">" ' . escapeshellarg($file), $headers);

    // Easiest case: if there is only one query header then show it.
    if (sizeof($headers) == 1 AND isset($headers[0])) {
      return ltrim($headers[0], '>');
    }
    // If we have at least one header then show that along with the count of queries.
    elseif (isset($headers[0])) {
      return sizeof($headers) . ' queries including "' . ltrim($headers[0], '>') . '"';
    }
    // If they provided a sequence with no header.
    elseif (empty($headers)) {
      return 'Unnamed Query';
    }
    // At the very least show the count of queries.
    else {
      return sizeof($headers) . ' queries';
    }
  }

  /**
   * Convert tsv blast output to gff output file.
   *
   * Created by Sofia Robb
   * 09/15/2016
   * counter bugfix 10/27/2016
   *
   * The subject (hit) will be the source feature.
   * The query will be the target.
   *
   * @todo: find a more efficient way since currently the first loop stores all the blast
   *   results into an array and then the second loop prints them.
   *
   * @param $blast_tsv
   *  The name of the blast tsv output file.
   * @param $blast_gff
   *  The name of the blast gff output file.
   */
  public function jobsConvertTSVtoGFF3($blast_tsv, $blast_gff){
    // Open a new file for writting the gff.
    $gff = fopen($blast_gff,"w");
    fwrite($gff,"##gff-version 3\n");

    // Open the TSV file to read from.
    $tsv = fopen($blast_tsv, "r") or die("Unable to open tsv file!");

    // For each line in the TSV file...
    // Need to go thru each line of tsv to find the first and last hsp of a hit.
    $last_s = NULL;
    $hsp = NULL;
    $HitResult = [];

    while(!feof($tsv)) {
      $line = fgets($tsv);
      $line = rtrim($line);

      // Skip the line if it's empty.
      if (preg_match('/^#/',$line) or preg_match('/^\s*$/',$line)){
        continue;
      }

      ## for keeping track of new queries and hits

      // Each line has the following parts:
      //  0: query id,
      //  1: subject id,
      //  2: % identity,
      //  3: alignment length,
      //  4: mismatches,
      //  5: gap opens,
      //  6: q. start,
      //  7: q. end,
      //  8: s. start,
      //  9: s. end,
      // 10: evalue,
      // 11: bit score
      $parts = preg_split('/\t/', $line);

      // Assign the important parts of the line to readable variables.
      $s = $parts[1];
      $q = $parts[0];
      $ss = $parts[8];
      $se = $parts[9];
      $qs = $parts[6];
      $qe = $parts[7];
      $e = $parts[10];


      // if this is a new hit print the last and
      // empty the $HitResult array and
      // reset hsp counter
      if ($last_s != NULL and $s != $last_s ) {
        self::jobsPrintGFFParentChildren($gff, $HitResult);
        $HitResult = [];
        $hsp=0;
      }

      // every line is a new hsp
      $hsp++;

      // determine query strand to use in match_part line, no need to store, just print
      $q_strand = '+';
      if ($qs > $qe) {
        list($qs, $qe) = [$qe, $qs];
        $q_strand = '-';
      }

      // determine subject (hit) strand to use in match line, needs to be stored
      $HitResult["$s,$q"]['strand'] = '+';
      list($start, $end) = [$ss, $se];
      if($ss > $se) {
        list($start, $end) = [$se, $ss];
        $HitResult["$s,$q"]['strand'] = '-';
      }

      // store smallest start
      if (!array_key_exists('SS',$HitResult["$s,$q"]) or $ss < $HitResult["$s,$q"]['SS']) {
        $HitResult["$s,$q"]['SS'] = $ss;
      }

      // store largest end
      if (!array_key_exists('SE',$HitResult["$s,$q"]) or $se > $HitResult["$s,$q"]['SE']) {
        $HitResult["$s,$q"]['SE'] = $se;
      }

      // store best evalue
      if (!array_key_exists('E',$HitResult["$s,$q"]) or $e < $HitResult["$s,$q"]['E']) {
        $HitResult["$s,$q"]['E'] = $e;
      }

      // generate the match_part line for each hsp
      $HitResult["$s,$q"]['HSPs'][] = join("\t", array($s, "BLASTRESULT" , "match_part" , $start , $end , $e , $HitResult["$s,$q"]['strand'] , '.' , "ID=$s.$q.$hsp;Parent=$s.$q;Target=$q $qs $qe $q_strand"));
      $last_s = $s;
    } // end tsv file while

    // print hit and hsp for the last hit
    self::jobsPrintGFFParentChildren($gff, $HitResult);

    // Close the files.
    fclose($tsv);
    fclose($gff);
  }

  /**
   * Prints the GFF parent feature and all of its children features
   *
   * @param $blast_feature_array
   *   an array of the all the child features which is used to generate the smallest
   *   and largest coordinates for the parent
   */
  public function jobsPrintGFFParentChildren($gff, $blast_feature_array){
    foreach ($blast_feature_array as $sq => $value ) {
      list ($s, $q) = preg_split('/,/' , $sq);
      $evalue =  $blast_feature_array["$s,$q"]['E'];
      $parent =  join("\t", array($s, "BLASTRESULT" , "match" , $blast_feature_array["$s,$q"]['SS'] , $blast_feature_array["$s,$q"]['SE'] , $blast_feature_array["$s,$q"]['E'] , $blast_feature_array["$s,$q"]['strand'] , '.' , "ID=$s.$q;Name=$q($evalue)")) . "\n";
      $child = join("\n",$blast_feature_array["$s,$q"]['HSPs']) . "\n";

      fwrite($gff,$parent);
      fwrite($gff,$child);
    }
  }
}
