# @file
# Tripal Blast Configuration Entity Schema

tripal_blast.database.*:
  type: config_entity
  label: 'BLAST Configuration Entity'
  mapping:
    id:
      type: 'integer'
      label: 'Database Entity ID'
    name:
      type: 'string'
      label: 'Name'
    path:
      type: 'string'
      label: 'Path'
    dbtype:
      type: 'string'
      label: 'Database Type'
    db_regexp:
      type: 'string'
      label: 'DB Regexp'
    db_id:
      type: 'string'
      label: 'DB Id'
    db_linkout_type:
      type: 'string'
      label: 'DB Link Type'
